import logging
from typing import Optional

from database import detect_price_change, get_history_prices, get_price_currency, is_target_met
from utils import format_price, today_str

logger = logging.getLogger(__name__)

DIVIDER = '<tr><td colspan="2" style="padding:0;"><div style="height:1px;background:rgba(99,102,241,0.12);margin:24px 0;"></div></td></tr>'

STORE_BADGES = {
    "steam": '<span style="display:inline-block;background:#1b2838;color:#66c0f4;padding:2px 12px;border-radius:20px;font-size:11px;font-weight:700;letter-spacing:0.5px;">STEAM</span>',
    "epic": '<span style="display:inline-block;background:#121212;color:#fff;padding:2px 12px;border-radius:20px;font-size:11px;font-weight:700;letter-spacing:0.5px;">EPIC</span>',
    "gog": '<span style="display:inline-block;background:#2b2b2b;color:#d2b48c;padding:2px 12px;border-radius:20px;font-size:11px;font-weight:700;letter-spacing:0.5px;">GOG</span>',
}

BASE_HTML = """<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#0b1120;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#0b1120;">
<tr><td align="center" style="padding:20px 12px;">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:linear-gradient(145deg,#1a2332,#0f172a);border-radius:18px;padding:28px;border:1px solid rgba(99,102,241,0.12);box-shadow:0 8px 32px rgba(0,0,0,0.4);">
<!-- HEADER -->
<tr><td style="text-align:center;padding-bottom:20px;">
<div style="font-size:36px;margin-bottom:6px;">🎮</div>
<h1 style="color:#f1f5f9;font-size:22px;margin:0;font-weight:800;letter-spacing:-0.5px;">Daily Game Price Report</h1>
<p style="color:#64748b;font-size:13px;margin:6px 0 0 0;">{date}</p>
</td></tr>
{body}
<!-- FOOTER -->
<tr><td style="text-align:center;padding-top:24px;">
<div style="height:1px;background:rgba(99,102,241,0.10);margin-bottom:20px;"></div>
<p style="color:#475569;font-size:11px;margin:0 0 4px;letter-spacing:0.5px;">GENERATED BY GAME PRICE TRACKER</p>
<p style="color:#334155;font-size:10px;margin:0 0 8px;">Checked: Steam &middot; Epic Games &middot; GOG</p>
<p style="color:#334155;font-size:10px;margin:0;">See you tomorrow!</p>
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>"""


def _store_badge(store: str) -> str:
    return STORE_BADGES.get(store, store.upper())


def _price_cell(price: Optional[float], currency: str) -> str:
    display = format_price(price, currency)
    color = "#f1f5f9"
    if display == "N/A":
        color = "#64748b"
    return f'<span style="color:{color};font-size:14px;font-weight:600;">{display}</span>'


def _target_status(game: dict) -> str:
    target = game.get("target_price")
    current = game.get("current_price")
    currency = game.get("current_currency", "INR")
    target_currency = get_price_currency(game, "target_price")
    reached = is_target_met(current, currency, target, target_currency)
    if reached and target is not None:
        return '<span style="color:#22c55e;font-weight:700;">✅ At or Below Target</span>'
    if target is not None and current is not None and target_currency == currency and target > 0:
        diff = abs(current - target)
        above = current > target
        direction = "above" if above else "below"
        color = "#ef4444" if above else "#f59e0b"
        return f'<span style="color:{color};font-size:13px;font-weight:600;">₹{diff:,.0f} {direction} target</span>'
    if target is None:
        return '<span style="color:#64748b;font-size:12px;">No target set</span>'
    return '<span style="color:#64748b;font-size:12px;">N/A</span>'


def _build_section(title: str, icon: str, content: str) -> str:
    return f"""<tr><td style="padding-bottom:8px;">
<h2 style="color:#f1f5f9;font-size:16px;margin:0 0 12px;font-weight:700;">{icon} {title}</h2>
{content}
</td></tr>"""


def _dashboard_section(games: list[dict], history: dict) -> str:
    total = len(games)
    on_sale_count = 0
    changed_count = 0
    new_low_count = 0
    cheapest = None
    cheapest_price = None
    most_expensive = None
    most_expensive_price = None

    for g in games:
        cid = g["id"]
        current = g.get("current_price")
        curr_currency = g.get("current_currency", "INR")

        if current is not None:
            if cheapest_price is None or current < cheapest_price:
                cheapest_price = current
                cheapest = g
            if most_expensive_price is None or current > most_expensive_price:
                most_expensive_price = current
                most_expensive = g

        diff = detect_price_change(history, cid, current, curr_currency)
        if diff is not None and diff != 0:
            changed_count += 1
            if diff < 0:
                on_sale_count += 1

        hist_prices = get_history_prices(history, cid)
        if current is not None and len(hist_prices) >= 2:
            prev_lowest = min(hist_prices[:-1])
            if current < prev_lowest:
                new_low_count += 1

    free_count = sum(1 for g in games if g.get("current_price") is not None and g["current_price"] == 0)

    cards = [
        ("🎮", "Tracked", str(total), ""),
        ("🏷️", "On Sale", str(on_sale_count), "#22c55e"),
        ("📉", "Price Changed", str(changed_count), "#f59e0b"),
        ("🏆", "New Lows", str(new_low_count), "#8b5cf6"),
    ]
    cards_html = ""
    for icon, label, value, color in cards:
        val_color = color or "#f1f5f9"
        cards_html += f"""<td style="width:25%;padding:6px;text-align:center;">
<table cellpadding="10" cellspacing="0" style="width:100%;background:rgba(15,23,42,0.6);border-radius:12px;">
<tr><td style="text-align:center;">
<div style="font-size:20px;margin-bottom:2px;">{icon}</div>
<div style="color:{val_color};font-size:22px;font-weight:800;">{value}</div>
<div style="color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:0.3px;">{label}</div>
</td></tr></table></td>"""

    extras = ""
    if cheapest and cheapest_price is not None:
        extras += f'<p style="color:#94a3b8;font-size:13px;margin:8px 0 0;">Cheapest: <strong style="color:#22c55e;">{cheapest.get("name","?")}</strong> — {format_price(cheapest_price, cheapest.get("current_currency","INR"))}</p>'
    if most_expensive and most_expensive_price is not None:
        extras += f'<p style="color:#94a3b8;font-size:13px;margin:4px 0 0;">Most expensive: <strong style="color:#ef4444;">{most_expensive.get("name","?")}</strong> — {format_price(most_expensive_price, most_expensive.get("current_currency","INR"))}</p>'
    if free_count > 0:
        extras += f'<p style="color:#94a3b8;font-size:13px;margin:4px 0 0;">Free games tracked: <strong style="color:#22c55e;">{free_count}</strong></p>'

    return f"""<table width="100%" cellpadding="0" cellspacing="0"><tr>{cards_html}</tr></table>{extras}"""


def _tracked_games_section(games: list[dict]) -> str:
    if not games:
        return '<p style="color:#64748b;font-size:13px;">No games are being tracked yet.</p>'

    rows = ""
    for g in games:
        name = g.get("name", "Unknown")
        store = g.get("store", "")
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        lowest = g.get("lowest_price")
        lowest_currency = get_price_currency(g, "lowest_price")
        target = g.get("target_price")
        cover = g.get("cover_image", "")
        status = _target_status(g)

        cover_html = ""
        if cover:
            cover_html = f'<img src="{cover}" alt="" style="width:44px;height:25px;border-radius:6px;object-fit:cover;display:block;">'
        else:
            cover_html = '<div style="width:44px;height:25px;background:rgba(30,41,59,0.5);border-radius:6px;"></div>'

        rows += f"""<tr>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;width:50px;">{cover_html}</td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;">
<div style="color:#f1f5f9;font-size:13px;font-weight:600;">{name}</div>
<div style="margin-top:2px;">{_store_badge(store)}</div>
</td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;text-align:right;white-space:nowrap;">{_price_cell(current, currency)}</td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;text-align:right;white-space:nowrap;"><span style="color:#22c55e;font-size:12px;font-weight:600;">{format_price(lowest, lowest_currency)}</span></td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;text-align:right;white-space:nowrap;"><span style="color:#f59e0b;font-size:12px;font-weight:600;">{format_price(target, get_price_currency(g, "target_price")) if target is not None else '<span style="color:#475569;">—</span>'}</span></td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;text-align:right;white-space:nowrap;font-size:12px;">{status}</td>
</tr>"""

    return f"""<table width="100%" cellpadding="0" cellspacing="0">
<tr style="color:#64748b;font-size:10px;text-transform:uppercase;letter-spacing:0.5px;">
<th style="text-align:left;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);width:50px;"></th>
<th style="text-align:left;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Game</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Current</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Lowest</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Target</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Status</th>
</tr>{rows}</table>"""


def _price_changes_section(games: list[dict], history: dict) -> str:
    changes = []
    for g in games:
        cid = g["id"]
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        diff = detect_price_change(history, cid, current, currency)
        if diff is None or diff == 0:
            continue
        name = g.get("name", "Unknown")
        store = g.get("store", "")
        hist_prices = get_history_prices(history, cid)
        prev_price = hist_prices[-2] if len(hist_prices) >= 2 else None
        changes.append((diff, name, store, current, prev_price, currency))

    if not changes:
        return '<p style="color:#64748b;font-size:13px;">No price changes in the last 24 hours.</p>'

    changes.sort(key=lambda x: x[0])  # biggest drop first

    items = ""
    for diff, name, store, current, prev_price, currency in changes:
        is_drop = diff < 0
        arrow = "▼" if is_drop else "▲"
        color = "#22c55e" if is_drop else "#ef4444"
        current_str = format_price(current, currency)
        prev_str = format_price(prev_price, currency) if prev_price is not None else "?"
        items += f"""<tr>
<td style="padding:8px 4px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;width:24px;text-align:center;"><span style="color:{color};font-size:13px;">{arrow}</span></td>
<td style="padding:8px 4px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;">
<div style="color:#f1f5f9;font-size:13px;font-weight:600;">{name}</div>
<div style="margin-top:1px;">{_store_badge(store)}</div>
</td>
<td style="padding:8px 4px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;text-align:right;white-space:nowrap;">
<span style="color:#94a3b8;font-size:13px;">{prev_str}</span>
<span style="color:#475569;font-size:11px;padding:0 4px;">→</span>
<span style="color:{color};font-size:14px;font-weight:700;">{current_str}</span>
</td>
</tr>"""

    return f"""<table width="100%" cellpadding="0" cellspacing="0">
<tr style="color:#64748b;font-size:10px;text-transform:uppercase;letter-spacing:0.5px;">
<th style="text-align:left;padding:4px 4px 8px;border-bottom:1px solid rgba(51,65,85,0.3);width:24px;"></th>
<th style="text-align:left;padding:4px 4px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Game</th>
<th style="text-align:right;padding:4px 4px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Price</th>
</tr>{items}</table>"""


def _new_lows_section(games: list[dict], history: dict) -> str:
    entries = []
    for g in games:
        cid = g["id"]
        current = g.get("current_price")
        if current is None:
            continue
        hist_prices = get_history_prices(history, cid)
        if len(hist_prices) < 2:
            continue
        prev_lowest = min(hist_prices[:-1])
        if current < prev_lowest:
            currency = g.get("current_currency", "INR")
            entries.append((g.get("name", "?"), g.get("store", ""), prev_lowest, current, currency))

    if not entries:
        return '<p style="color:#64748b;font-size:13px;">No new all-time lows today.</p>'

    items = ""
    for name, store, old_low, new_low, currency in entries:
        items += f"""<tr>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;width:30px;text-align:center;"><span style="font-size:16px;">🏆</span></td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;">
<div style="color:#f1f5f9;font-size:14px;font-weight:700;">{name}</div>
<div style="margin-top:2px;">{_store_badge(store)}</div>
</td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;text-align:right;white-space:nowrap;">
<div style="color:#94a3b8;font-size:12px;">Old Lowest: <span style="color:#f1f5f9;font-weight:600;">{format_price(old_low, currency)}</span></div>
<div style="color:#22c55e;font-size:14px;font-weight:700;">New Lowest: {format_price(new_low, currency)}</div>
</td>
</tr>"""

    return f"""<table width="100%" cellpadding="0" cellspacing="0">
<tr style="color:#64748b;font-size:10px;text-transform:uppercase;letter-spacing:0.5px;">
<th style="padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);width:30px;"></th>
<th style="text-align:left;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Game</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Price</th>
</tr>{items}</table>"""


def _buy_recs_section(games: list[dict], history: dict) -> str:
    recs = []
    for g in games:
        name = g.get("name", "?")
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        lowest = g.get("lowest_price")
        target = g.get("target_price")
        target_currency = get_price_currency(g, "target_price")
        reached = is_target_met(current, currency, target, target_currency)

        reason = None
        if current is not None and lowest is not None and current == lowest and current > 0:
            reason = "All-time low! This is the best price ever recorded for this game."
            recs.append(("🔥", name, reason, "#22c55e"))
        elif reached and target is not None:
            reason = "Price is at or below your target. Great time to buy!"
            recs.append(("🔥", name, reason, "#22c55e"))
        elif current is not None and lowest is not None and current <= lowest * 1.05 and current > 0:
            reason = "Very close to the lowest recorded price. Worth considering."
            recs.append(("👍", name, reason, "#f59e0b"))

    if not recs:
        return """<p style="color:#64748b;font-size:13px;">No exceptional deals today.</p>
<p style="color:#475569;font-size:12px;margin-top:4px;">You may want to wait for larger sales or set a target price and we'll alert you when it's reached.</p>"""

    items = ""
    for icon, name, reason, color in recs[:5]:
        items += f"""<tr>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:top;width:30px;text-align:center;"><span style="font-size:18px;">{icon}</span></td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:top;">
<div style="color:#f1f5f9;font-size:14px;font-weight:700;">{name}</div>
<p style="color:#94a3b8;font-size:12px;margin:2px 0 0;line-height:1.4;">{reason}</p>
</td>
</tr>"""

    return f"""<table width="100%" cellpadding="0" cellspacing="0">{items}</table>"""


def _wishlist_section(games: list[dict]) -> str:
    items = ""
    for g in games:
        name = g.get("name", "?")
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        target = g.get("target_price")
        target_currency = get_price_currency(g, "target_price")
        if target is None or current is None or target_currency != currency or target <= 0:
            continue
        reached = is_target_met(current, currency, target, target_currency)
        if reached:
            pct = 100
            bar_color = "#22c55e"
            label = "✅ Target Reached"
        else:
            pct = min(int((1 - (current - target) / target) * 100), 99)
            if pct < 0:
                pct = 0
            bar_color = "#8b5cf6"
            label = f"₹{current - target:,.0f} away"
        fill = f'<div style="width:{pct}%;height:8px;background:{bar_color};border-radius:4px;min-width:4px;"></div>'
        items += f"""<tr>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;">
<div style="color:#f1f5f9;font-size:13px;font-weight:600;">{name}</div>
</td>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;">
<div style="background:rgba(15,23,42,0.6);border-radius:4px;height:8px;overflow:hidden;">{fill}</div>
</td>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;text-align:right;white-space:nowrap;">
<div style="color:#f1f5f9;font-size:12px;">{format_price(current, currency)} → {format_price(target, currency)}</div>
<div style="color:#94a3b8;font-size:11px;">{label}</div>
</td>
</tr>"""

    if not items:
        return '<p style="color:#64748b;font-size:13px;">No target prices set. Add target prices to track your wish list progress.</p>'

    return f"""<table width="100%" cellpadding="0" cellspacing="0">
<tr style="color:#64748b;font-size:10px;text-transform:uppercase;letter-spacing:0.5px;">
<th style="text-align:left;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Game</th>
<th style="padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Progress</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Current → Target</th>
</tr>{items}</table>"""


def _insights_section(games: list[dict], history: dict) -> str:
    price_drops = []
    price_hikes = []
    store_discounts: dict[str, int] = {}
    total_current = 0.0
    count_with_price = 0
    free_count = 0

    for g in games:
        cid = g["id"]
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        store = g.get("store", "")
        diff = detect_price_change(history, cid, current, currency)

        if diff is not None:
            if diff < 0:
                price_drops.append((diff, g.get("name", "?"), format_price(abs(diff), currency)))
                store_discounts[store] = store_discounts.get(store, 0) + 1
            elif diff > 0:
                price_hikes.append((diff, g.get("name", "?"), format_price(diff, currency)))

        if current is not None:
            total_current += current
            count_with_price += 1
            if current == 0:
                free_count += 1

    avg_price = total_current / count_with_price if count_with_price > 0 else None
    insights = []
    if price_drops:
        price_drops.sort(key=lambda x: x[0])
        biggest = price_drops[0]
        insights.append(f'Biggest drop: <strong style="color:#22c55e;">▼ {biggest[2]}</strong> — {biggest[1]}')
    else:
        insights.append("No price drops today.")

    if price_hikes:
        price_hikes.sort(key=lambda x: x[0], reverse=True)
        biggest = price_hikes[0]
        insights.append(f'Biggest increase: <strong style="color:#ef4444;">▲ {biggest[2]}</strong> — {biggest[1]}')
    else:
        insights.append("No price increases today.")

    if store_discounts:
        best_store = max(store_discounts, key=store_discounts.get)
        best_count = store_discounts[best_store]
        insights.append(f'Store with most discounts: <strong>{best_store.upper()}</strong> ({best_count})')
    else:
        insights.append("No store has discounts today.")

    if avg_price is not None:
        insights.append(f"Average tracked price: <strong>{format_price(avg_price, 'INR')}</strong>")
    if free_count > 0:
        insights.append(f"Free games: <strong style='color:#22c55e;'>{free_count}</strong>")

    items = "".join(f'<li style="color:#94a3b8;font-size:13px;margin-bottom:6px;line-height:1.4;">{i}</li>' for i in insights)
    return f"""<table width="100%" cellpadding="0" cellspacing="0" style="background:rgba(15,23,42,0.4);border-radius:12px;padding:4px 12px;">
<tr><td><ul style="list-style:none;padding:0;margin:8px 0;">{items}</ul></td></tr>
</table>"""


def build_daily_report(games: list[dict], history: dict) -> str:
    sections = [
        _build_section("Dashboard Summary", "📊", _dashboard_section(games, history)),
        DIVIDER,
        _build_section("Tracked Games", "📋", _tracked_games_section(games)),
        DIVIDER,
        _build_section("Price Changes", "📈", _price_changes_section(games, history)),
        DIVIDER,
        _build_section("New Lowest Prices", "🏆", _new_lows_section(games, history)),
        DIVIDER,
        _build_section("Buy Recommendations", "🔥", _buy_recs_section(games, history)),
        DIVIDER,
        _build_section("Wish List Progress", "🎯", _wishlist_section(games)),
        DIVIDER,
        _build_section("Historical Insights", "📊", _insights_section(games, history)),
    ]

    body = "\n".join(sections)
    return BASE_HTML.format(date=today_str(), body=body)
