import logging
from typing import Optional

from database import (
    detect_price_change, get_history_prices, get_price_currency, is_target_met,
    HISTORY_SALE_KEY, group_games_by_identity,
)
from utils import format_price, today_str

logger = logging.getLogger(__name__)

DIVIDER = '<tr><td colspan="2" style="padding:0;"><div style="height:1px;background:rgba(99,102,241,0.12);margin:24px 0;"></div></td></tr>'

STORE_BADGES = {
    "steam": '<span style="display:inline-block;background:#1b2838;color:#66c0f4;padding:2px 12px;border-radius:20px;font-size:11px;font-weight:700;letter-spacing:0.5px;">STEAM</span>',
    "epic": '<span style="display:inline-block;background:#121212;color:#fff;padding:2px 12px;border-radius:20px;font-size:11px;font-weight:700;letter-spacing:0.5px;">EPIC</span>',
    "gog": '<span style="display:inline-block;background:#2b2b2b;color:#d2b48c;padding:2px 12px;border-radius:20px;font-size:11px;font-weight:700;letter-spacing:0.5px;">GOG</span>',
}

BASE_HTML = """<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#0b1120;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#0b1120;">
<tr><td align="center" style="padding:20px 12px;">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:linear-gradient(145deg,#1a2332,#0f172a);border-radius:18px;padding:28px;border:1px solid rgba(99,102,241,0.12);box-shadow:0 8px 32px rgba(0,0,0,0.4);">
<!-- HEADER -->
<tr><td style="text-align:center;padding-bottom:20px;">
<div style="font-size:36px;margin-bottom:6px;">🎮</div>
<h1 style="color:#f1f5f9;font-size:22px;margin:0;font-weight:800;letter-spacing:-0.5px;">Daily Game Price Report</h1>
<p style="color:#64748b;font-size:13px;margin:6px 0 0 0;">{date}</p>
</td></tr>
{body}
<!-- FOOTER -->
<tr><td style="text-align:center;padding-top:24px;">
<div style="height:1px;background:rgba(99,102,241,0.10);margin-bottom:20px;"></div>
<p style="color:#475569;font-size:11px;margin:0 0 4px;letter-spacing:0.5px;">GENERATED BY GAME PRICE TRACKER</p>
<p style="color:#334155;font-size:10px;margin:0 0 8px;">Checked: Steam &middot; Epic Games &middot; GOG</p>
<p style="color:#334155;font-size:10px;margin:0;">See you tomorrow!</p>
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>"""


def _store_badge(store: str) -> str:
    return STORE_BADGES.get(store, store.upper())


def _price_cell(price: Optional[float], currency: str) -> str:
    display = format_price(price, currency)
    color = "#f1f5f9"
    if display == "N/A":
        color = "#64748b"
    return f'<span style="color:{color};font-size:14px;font-weight:600;">{display}</span>'


def _target_status(game: dict) -> str:
    target = game.get("target_price")
    current = game.get("current_price")
    currency = game.get("current_currency", "INR")
    target_currency = get_price_currency(game, "target_price")
    reached = is_target_met(current, currency, target, target_currency)
    if reached and target is not None:
        return '<span style="color:#22c55e;font-weight:700;">✅ At or Below Target</span>'
    if target is not None and current is not None and target_currency == currency and target > 0:
        diff = abs(current - target)
        above = current > target
        direction = "above" if above else "below"
        color = "#ef4444" if above else "#f59e0b"
        return f'<span style="color:{color};font-size:13px;font-weight:600;">₹{diff:,.0f} {direction} target</span>'
    if target is None:
        return '<span style="color:#64748b;font-size:12px;">No target set</span>'
    return '<span style="color:#64748b;font-size:12px;">N/A</span>'


def _build_section(title: str, icon: str, content: str) -> str:
    return f"""<tr><td style="padding-bottom:8px;">
<h2 style="color:#f1f5f9;font-size:16px;margin:0 0 12px;font-weight:700;">{icon} {title}</h2>
{content}
</td></tr>"""


STORE_NAMES = {"steam": "Steam", "epic": "Epic Games", "gog": "GOG"}


def _cross_store_deals_section(games: list[dict]) -> str:
    """Best cross-store deals for games tracked on both Steam and Epic."""
    grouped = group_games_by_identity(games)
    blocks = []

    for listings in grouped.values():
        steam = next((g for g in listings if g.get("store") == "steam"), None)
        epic = next((g for g in listings if g.get("store") == "epic"), None)
        if not steam or not epic:
            continue

        name = steam.get("name") or epic.get("name") or "Unknown"
        rows = []
        cheapest_store = None
        cheapest_price = None

        for label, g in (("Steam", steam), ("Epic", epic)):
            current = g.get("current_price")
            currency = g.get("current_currency", "INR")
            disc = g.get("discount_percent") or 0
            price_str = format_price(current, currency)
            if disc > 0:
                price_str += f" (-{disc}%)"
            rows.append(f"{label}: {price_str}")
            if current is not None and (cheapest_price is None or current < cheapest_price):
                cheapest_price = current
                cheapest_store = label

        winner = ""
        if cheapest_store and steam.get("current_price") is not None and epic.get("current_price") is not None:
            prices = [steam.get("current_price"), epic.get("current_price")]
            if max(prices) > min(prices):
                winner = f"<p style=\"color:#22c55e;font-size:13px;margin:8px 0 0;\">🏆 Cheapest: <strong>{cheapest_store}</strong></p>"

        blocks.append(
            f"<div style=\"margin-bottom:16px;padding-bottom:12px;border-bottom:1px solid rgba(51,65,85,0.25);\">"
            f"<div style=\"color:#f1f5f9;font-size:15px;font-weight:700;margin-bottom:6px;\">{name}</div>"
            f"<div style=\"color:#94a3b8;font-size:13px;line-height:1.6;\">{'<br>'.join(rows)}</div>"
            f"{winner}</div>"
        )

    if not blocks:
        return '<p style="color:#64748b;font-size:13px;">No games tracked on both Steam and Epic yet.</p>'
    return "".join(blocks[:10])


def _new_sales_today_section(games: list[dict]) -> str:
    today = today_str()
    new_sales = [
        g for g in games
        if g.get("is_on_sale") and g.get("sale_started") == today
    ]
    if not new_sales:
        return '<p style="color:#64748b;font-size:13px;">No new sales started today.</p>'

    rows = ""
    for g in new_sales:
        name = g.get("name", "?")
        store = STORE_NAMES.get(g.get("store", ""), g.get("store", ""))
        disc = g.get("discount_percent") or 0
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        rows += f"""<tr>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);">{name}</td>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);">{store}</td>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);text-align:right;color:#22c55e;font-weight:700;">-{disc}%</td>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);text-align:right;">{format_price(current, currency)}</td>
</tr>"""

    return f"""<table width="100%" cellpadding="0" cellspacing="0">
<tr style="color:#64748b;font-size:10px;text-transform:uppercase;">
<th style="text-align:left;padding:4px 6px 8px;">Game</th>
<th style="text-align:left;padding:4px 6px 8px;">Store</th>
<th style="text-align:right;padding:4px 6px 8px;">Discount</th>
<th style="text-align:right;padding:4px 6px 8px;">Current Price</th>
</tr>{rows}</table>"""


def _dashboard_section(games: list[dict], history: dict) -> str:
    total = len(games)
    on_sale_count = 0
    changed_count = 0
    new_low_count = 0
    cheapest = None
    cheapest_price = None
    most_expensive = None
    most_expensive_price = None

    for g in games:
        cid = g["id"]
        current = g.get("current_price")
        curr_currency = g.get("current_currency", "INR")

        if g.get("is_on_sale"):
            on_sale_count += 1

        if current is not None:
            if cheapest_price is None or current < cheapest_price:
                cheapest_price = current
                cheapest = g
            if most_expensive_price is None or current > most_expensive_price:
                most_expensive_price = current
                most_expensive = g

        diff = detect_price_change(history, cid, current, curr_currency)
        if diff is not None and diff != 0:
            changed_count += 1

        hist_prices = get_history_prices(history, cid)
        if current is not None and len(hist_prices) >= 2:
            prev_lowest = min(hist_prices[:-1])
            if current < prev_lowest:
                new_low_count += 1

    free_count = sum(1 for g in games if g.get("current_price") is not None and g["current_price"] == 0)

    on_sale_list = [g for g in games if g.get("is_on_sale")]
    biggest_discount = max((g.get("discount_percent") or 0 for g in on_sale_list), default=0)
    avg_discount = (
        round(sum(g.get("discount_percent") or 0 for g in on_sale_list) / len(on_sale_list))
        if on_sale_list else 0
    )

    cards = [
        ("🎮", "Tracked", str(total), ""),
        ("🔥", "Games On Sale", str(on_sale_count), "#22c55e"),
        ("📉", "Price Changed", str(changed_count), "#f59e0b"),
        ("🏆", "New Lows", str(new_low_count), "#8b5cf6"),
    ]
    cards_html = ""
    for icon, label, value, color in cards:
        val_color = color or "#f1f5f9"
        cards_html += f"""<td style="width:25%;padding:6px;text-align:center;">
<table cellpadding="10" cellspacing="0" style="width:100%;background:rgba(15,23,42,0.6);border-radius:12px;">
<tr><td style="text-align:center;">
<div style="font-size:20px;margin-bottom:2px;">{icon}</div>
<div style="color:{val_color};font-size:22px;font-weight:800;">{value}</div>
<div style="color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:0.3px;">{label}</div>
</td></tr></table></td>"""

    extras = ""
    if cheapest and cheapest_price is not None:
        extras += f'<p style="color:#94a3b8;font-size:13px;margin:8px 0 0;">Cheapest: <strong style="color:#22c55e;">{cheapest.get("name","?")}</strong> — {format_price(cheapest_price, cheapest.get("current_currency","INR"))}</p>'
    if most_expensive and most_expensive_price is not None:
        extras += f'<p style="color:#94a3b8;font-size:13px;margin:4px 0 0;">Most expensive: <strong style="color:#ef4444;">{most_expensive.get("name","?")}</strong> — {format_price(most_expensive_price, most_expensive.get("current_currency","INR"))}</p>'
    if free_count > 0:
        extras += f'<p style="color:#94a3b8;font-size:13px;margin:4px 0 0;">Free games tracked: <strong style="color:#22c55e;">{free_count}</strong></p>'
    if on_sale_list:
        extras += f'<p style="color:#94a3b8;font-size:13px;margin:4px 0 0;">Biggest discount: <strong style="color:#22c55e;">{biggest_discount}%</strong> &middot; Average discount: <strong style="color:#22c55e;">{avg_discount}%</strong></p>'

    return f"""<table width="100%" cellpadding="0" cellspacing="0"><tr>{cards_html}</tr></table>{extras}"""


def _tracked_games_section(games: list[dict]) -> str:
    if not games:
        return '<p style="color:#64748b;font-size:13px;">No games are being tracked yet.</p>'

    rows = ""
    for g in games:
        name = g.get("name", "Unknown")
        store = g.get("store", "")
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        lowest = g.get("lowest_price")
        lowest_currency = get_price_currency(g, "lowest_price")
        target = g.get("target_price")
        cover = g.get("cover_image", "")
        status = _target_status(g)

        cover_html = ""
        if cover:
            cover_html = f'<img src="{cover}" alt="" style="width:44px;height:25px;border-radius:6px;object-fit:cover;display:block;">'
        else:
            cover_html = '<div style="width:44px;height:25px;background:rgba(30,41,59,0.5);border-radius:6px;"></div>'

        rows += f"""<tr>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;width:50px;">{cover_html}</td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;">
<div style="color:#f1f5f9;font-size:13px;font-weight:600;">{name}</div>
<div style="margin-top:2px;">{_store_badge(store)}</div>
</td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;text-align:right;white-space:nowrap;">{_price_cell(current, currency)}</td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;text-align:right;white-space:nowrap;"><span style="color:#22c55e;font-size:12px;font-weight:600;">{format_price(lowest, lowest_currency)}</span></td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;text-align:right;white-space:nowrap;"><span style="color:#f59e0b;font-size:12px;font-weight:600;">{format_price(target, get_price_currency(g, "target_price")) if target is not None else '<span style="color:#475569;">—</span>'}</span></td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.25);vertical-align:middle;text-align:right;white-space:nowrap;font-size:12px;">{status}</td>
</tr>"""

    return f"""<table width="100%" cellpadding="0" cellspacing="0">
<tr style="color:#64748b;font-size:10px;text-transform:uppercase;letter-spacing:0.5px;">
<th style="text-align:left;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);width:50px;"></th>
<th style="text-align:left;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Game</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Current</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Lowest</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Target</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Status</th>
</tr>{rows}</table>"""


def _price_changes_section(games: list[dict], history: dict) -> str:
    changes = []
    for g in games:
        cid = g["id"]
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        diff = detect_price_change(history, cid, current, currency)
        if diff is None or diff == 0:
            continue
        name = g.get("name", "Unknown")
        store = g.get("store", "")
        hist_prices = get_history_prices(history, cid)
        prev_price = hist_prices[-2] if len(hist_prices) >= 2 else None
        changes.append((diff, name, store, current, prev_price, currency))

    if not changes:
        return '<p style="color:#64748b;font-size:13px;">No price changes in the last 24 hours.</p>'

    changes.sort(key=lambda x: x[0])  # biggest drop first

    items = ""
    for diff, name, store, current, prev_price, currency in changes:
        is_drop = diff < 0
        arrow = "▼" if is_drop else "▲"
        color = "#22c55e" if is_drop else "#ef4444"
        current_str = format_price(current, currency)
        prev_str = format_price(prev_price, currency) if prev_price is not None else "?"
        items += f"""<tr>
<td style="padding:8px 4px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;width:24px;text-align:center;"><span style="color:{color};font-size:13px;">{arrow}</span></td>
<td style="padding:8px 4px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;">
<div style="color:#f1f5f9;font-size:13px;font-weight:600;">{name}</div>
<div style="margin-top:1px;">{_store_badge(store)}</div>
</td>
<td style="padding:8px 4px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;text-align:right;white-space:nowrap;">
<span style="color:#94a3b8;font-size:13px;">{prev_str}</span>
<span style="color:#475569;font-size:11px;padding:0 4px;">→</span>
<span style="color:{color};font-size:14px;font-weight:700;">{current_str}</span>
</td>
</tr>"""

    return f"""<table width="100%" cellpadding="0" cellspacing="0">
<tr style="color:#64748b;font-size:10px;text-transform:uppercase;letter-spacing:0.5px;">
<th style="text-align:left;padding:4px 4px 8px;border-bottom:1px solid rgba(51,65,85,0.3);width:24px;"></th>
<th style="text-align:left;padding:4px 4px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Game</th>
<th style="text-align:right;padding:4px 4px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Price</th>
</tr>{items}</table>"""


def _new_lows_section(games: list[dict], history: dict) -> str:
    entries = []
    for g in games:
        cid = g["id"]
        current = g.get("current_price")
        if current is None:
            continue
        hist_prices = get_history_prices(history, cid)
        if len(hist_prices) < 2:
            continue
        prev_lowest = min(hist_prices[:-1])
        if current < prev_lowest:
            currency = g.get("current_currency", "INR")
            entries.append((g.get("name", "?"), g.get("store", ""), prev_lowest, current, currency))

    if not entries:
        return '<p style="color:#64748b;font-size:13px;">No new all-time lows today.</p>'

    items = ""
    for name, store, old_low, new_low, currency in entries:
        items += f"""<tr>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;width:30px;text-align:center;"><span style="font-size:16px;">🏆</span></td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;">
<div style="color:#f1f5f9;font-size:14px;font-weight:700;">{name}</div>
<div style="margin-top:2px;">{_store_badge(store)}</div>
</td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;text-align:right;white-space:nowrap;">
<div style="color:#94a3b8;font-size:12px;">Old Lowest: <span style="color:#f1f5f9;font-weight:600;">{format_price(old_low, currency)}</span></div>
<div style="color:#22c55e;font-size:14px;font-weight:700;">New Lowest: {format_price(new_low, currency)}</div>
</td>
</tr>"""

    return f"""<table width="100%" cellpadding="0" cellspacing="0">
<tr style="color:#64748b;font-size:10px;text-transform:uppercase;letter-spacing:0.5px;">
<th style="padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);width:30px;"></th>
<th style="text-align:left;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Game</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Price</th>
</tr>{items}</table>"""


def _buy_recs_section(games: list[dict], history: dict) -> str:
    recs = []
    for g in games:
        name = g.get("name", "?")
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        lowest = g.get("lowest_price")
        target = g.get("target_price")
        target_currency = get_price_currency(g, "target_price")
        reached = is_target_met(current, currency, target, target_currency)

        reason = None
        if current is not None and lowest is not None and current == lowest and current > 0:
            reason = "All-time low! This is the best price ever recorded for this game."
            recs.append(("🔥", name, reason, "#22c55e"))
        elif reached and target is not None:
            reason = "Price is at or below your target. Great time to buy!"
            recs.append(("🔥", name, reason, "#22c55e"))
        elif current is not None and lowest is not None and current <= lowest * 1.05 and current > 0:
            reason = "Very close to the lowest recorded price. Worth considering."
            recs.append(("👍", name, reason, "#f59e0b"))

    if not recs:
        return """<p style="color:#64748b;font-size:13px;">No exceptional deals today.</p>
<p style="color:#475569;font-size:12px;margin-top:4px;">You may want to wait for larger sales or set a target price and we'll alert you when it's reached.</p>"""

    items = ""
    for icon, name, reason, color in recs[:5]:
        items += f"""<tr>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:top;width:30px;text-align:center;"><span style="font-size:18px;">{icon}</span></td>
<td style="padding:10px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:top;">
<div style="color:#f1f5f9;font-size:14px;font-weight:700;">{name}</div>
<p style="color:#94a3b8;font-size:12px;margin:2px 0 0;line-height:1.4;">{reason}</p>
</td>
</tr>"""

    return f"""<table width="100%" cellpadding="0" cellspacing="0">{items}</table>"""


def _wishlist_section(games: list[dict]) -> str:
    items = ""
    for g in games:
        name = g.get("name", "?")
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        target = g.get("target_price")
        target_currency = get_price_currency(g, "target_price")
        if target is None or current is None or target_currency != currency or target <= 0:
            continue
        reached = is_target_met(current, currency, target, target_currency)
        if reached:
            pct = 100
            bar_color = "#22c55e"
            label = "✅ Target Reached"
        else:
            pct = min(int((1 - (current - target) / target) * 100), 99)
            if pct < 0:
                pct = 0
            bar_color = "#8b5cf6"
            label = f"₹{current - target:,.0f} away"
        fill = f'<div style="width:{pct}%;height:8px;background:{bar_color};border-radius:4px;min-width:4px;"></div>'
        items += f"""<tr>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;">
<div style="color:#f1f5f9;font-size:13px;font-weight:600;">{name}</div>
</td>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;">
<div style="background:rgba(15,23,42,0.6);border-radius:4px;height:8px;overflow:hidden;">{fill}</div>
</td>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;text-align:right;white-space:nowrap;">
<div style="color:#f1f5f9;font-size:12px;">{format_price(current, currency)} → {format_price(target, currency)}</div>
<div style="color:#94a3b8;font-size:11px;">{label}</div>
</td>
</tr>"""

    if not items:
        return '<p style="color:#64748b;font-size:13px;">No target prices set. Add target prices to track your wish list progress.</p>'

    return f"""<table width="100%" cellpadding="0" cellspacing="0">
<tr style="color:#64748b;font-size:10px;text-transform:uppercase;letter-spacing:0.5px;">
<th style="text-align:left;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Game</th>
<th style="padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Progress</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Current → Target</th>
</tr>{items}</table>"""


def _sales_section(games: list[dict], history: dict) -> str:
    on_sale = [g for g in games if g.get("is_on_sale")]
    on_sale.sort(key=lambda g: (g.get("discount_percent") or 0), reverse=True)

    items = ""
    if on_sale:
        for g in on_sale:
            name = g.get("name", "?")
            store = g.get("store", "")
            disc = g.get("discount_percent") or 0
            current = g.get("current_price")
            currency = g.get("current_currency", "INR")
            items += f"""<tr>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;">
<div style="color:#f1f5f9;font-size:13px;font-weight:600;">{name}</div>
<div style="margin-top:1px;">{_store_badge(store)}</div>
</td>
<td style="padding:8px 6px;border-bottom:1px solid rgba(51,65,85,0.2);vertical-align:middle;text-align:right;white-space:nowrap;">
<span style="color:#22c55e;font-size:14px;font-weight:800;">-{disc}% OFF</span>
<div style="color:#94a3b8;font-size:12px;">{format_price(current, currency)}</div>
</td>
</tr>"""
        items = f"""<table width="100%" cellpadding="0" cellspacing="0">
<tr style="color:#64748b;font-size:10px;text-transform:uppercase;letter-spacing:0.5px;">
<th style="text-align:left;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Game</th>
<th style="text-align:right;padding:4px 6px 8px;border-bottom:1px solid rgba(51,65,85,0.3);">Discount</th>
</tr>{items}</table>"""
    else:
        items = '<p style="color:#64748b;font-size:13px;">No games are on sale right now.</p>'

    # Biggest discount today + sales that ended today, from history sale metadata.
    today_sales_ended = []
    for g in games:
        cid = g["id"]
        sales = (history.get(cid) or {}).get(HISTORY_SALE_KEY) or {}
        dates = sorted(k for k in sales if k != HISTORY_SALE_KEY) if isinstance(sales, dict) else []
        if g.get("is_on_sale"):
            continue
        # ended today if previously on sale and not now
        if len(dates) >= 2:
            prev_on = sales[dates[-2]].get("is_on_sale")
            now_on = sales[dates[-1]].get("is_on_sale")
            if prev_on and not now_on:
                today_sales_ended.append(g.get("name", "?"))
        elif len(dates) == 1 and not sales[dates[0]].get("is_on_sale") and g.get("sale_started") is None and g.get("discount_percent", 0) == 0:
            pass

    extras = ""
    if on_sale:
        top = on_sale[0]
        extras += f'<p style="color:#94a3b8;font-size:13px;margin:10px 0 0;">Biggest Discount Today: <strong style="color:#22c55e;">{top.get("discount_percent",0)}% — {top.get("name","?")}</strong></p>'
    if today_sales_ended:
        extras += f'<p style="color:#f59e0b;font-size:13px;margin:4px 0 0;">Sales ended today: <strong style="color:#ef4444;">{" &middot; ".join(today_sales_ended)}</strong></p>'

    return items + extras


def _insights_section(games: list[dict], history: dict) -> str:
    price_drops = []
    price_hikes = []
    store_discounts: dict[str, int] = {}
    total_current = 0.0
    count_with_price = 0
    free_count = 0

    for g in games:
        cid = g["id"]
        current = g.get("current_price")
        currency = g.get("current_currency", "INR")
        store = g.get("store", "")
        diff = detect_price_change(history, cid, current, currency)

        if diff is not None:
            if diff < 0:
                price_drops.append((diff, g.get("name", "?"), format_price(abs(diff), currency)))
                store_discounts[store] = store_discounts.get(store, 0) + 1
            elif diff > 0:
                price_hikes.append((diff, g.get("name", "?"), format_price(diff, currency)))

        if current is not None:
            total_current += current
            count_with_price += 1
            if current == 0:
                free_count += 1

    avg_price = total_current / count_with_price if count_with_price > 0 else None
    insights = []
    if price_drops:
        price_drops.sort(key=lambda x: x[0])
        biggest = price_drops[0]
        insights.append(f'Biggest drop: <strong style="color:#22c55e;">▼ {biggest[2]}</strong> — {biggest[1]}')
    else:
        insights.append("No price drops today.")

    if price_hikes:
        price_hikes.sort(key=lambda x: x[0], reverse=True)
        biggest = price_hikes[0]
        insights.append(f'Biggest increase: <strong style="color:#ef4444;">▲ {biggest[2]}</strong> — {biggest[1]}')
    else:
        insights.append("No price increases today.")

    if store_discounts:
        best_store = max(store_discounts, key=store_discounts.get)
        best_count = store_discounts[best_store]
        insights.append(f'Store with most discounts: <strong>{best_store.upper()}</strong> ({best_count})')
    else:
        insights.append("No store has discounts today.")

    if avg_price is not None:
        insights.append(f"Average tracked price: <strong>{format_price(avg_price, 'INR')}</strong>")
    if free_count > 0:
        insights.append(f"Free games: <strong style='color:#22c55e;'>{free_count}</strong>")

    items = "".join(f'<li style="color:#94a3b8;font-size:13px;margin-bottom:6px;line-height:1.4;">{i}</li>' for i in insights)
    return f"""<table width="100%" cellpadding="0" cellspacing="0" style="background:rgba(15,23,42,0.4);border-radius:12px;padding:4px 12px;">
<tr><td><ul style="list-style:none;padding:0;margin:8px 0;">{items}</ul></td></tr>
</table>"""


def build_daily_report(games: list[dict], history: dict, prefs: Optional[dict] = None) -> str:
    from database import DEFAULT_EMAIL_PREFERENCES, normalize_game
    from datetime import datetime

    if prefs is None:
        prefs = DEFAULT_EMAIL_PREFERENCES

    merged_prefs = dict(DEFAULT_EMAIL_PREFERENCES)
    merged_prefs.update(prefs)
    if "enabled_content" in prefs and isinstance(prefs["enabled_content"], dict):
        merged_prefs["enabled_content"] = dict(DEFAULT_EMAIL_PREFERENCES["enabled_content"])
        merged_prefs["enabled_content"].update(prefs["enabled_content"])

    enabled = merged_prefs["enabled_content"]
    theme_name = merged_prefs.get("theme", "Midnight")
    mode = merged_prefs.get("games_selection_mode", "all")
    selected_ids = set(merged_prefs.get("selected_game_ids", []))
    selected_tags = set(t.lower() for t in merged_prefs.get("selected_tags", []))
    featured_id = merged_prefs.get("featured_game_id")
    report_title = merged_prefs.get("report_title") or "🎮 Daily Game Drop"

    # Theme Styling Tokens
    from themes import THEMES, get_theme
    app_theme_id = merged_prefs.get("app_theme_id")

    if (theme_name == "Use application theme" or theme_name in THEMES) and (app_theme_id or theme_name in THEMES):
        target_id = app_theme_id if theme_name == "Use application theme" else theme_name
        t = get_theme(target_id)
        bg_body = "#0d121f" if "Midnight" in t["name"] else t.get("bg_container", "#0d121f")
        bg_container = t.get("bg_sidebar", "#090d16")
        bg_card = t.get("bg_container", "#121827")
        border_col = t.get("border_color", "#1f293d")
        text_title = t.get("text_primary", "#f8fafc")
        text_body = t.get("text_primary", "#cbd5e1")
        text_muted = t.get("text_secondary", "#94a3b8")
        accent_col = t.get("accent_color", "#6366f1")
        sale_green = t.get("sale_color", "#4ade80")
        sale_bg = t.get("sale_bg", "rgba(74, 222, 128, 0.12)")
        btn_bg = t.get("btn_primary_bg", "#4f46e5")
        btn_text = t.get("btn_primary_text", "#ffffff")
    elif theme_name == "Minimal":
        bg_body = "#ffffff"
        bg_container = "#f8fafc"
        bg_card = "#ffffff"
        border_col = "#e2e8f0"
        text_title = "#0f172a"
        text_body = "#334155"
        text_muted = "#64748b"
        accent_col = "#2563eb"
        sale_green = "#16a34a"
        sale_bg = "#f0fdf4"
        btn_bg = "#2563eb"
        btn_text = "#ffffff"
    elif theme_name == "Aurora":
        bg_body = "#090d16"
        bg_container = "#131b2e"
        bg_card = "#1a253d"
        border_col = "rgba(139, 92, 246, 0.25)"
        text_title = "#f8fafc"
        text_body = "#cbd5e1"
        text_muted = "#94a3b8"
        accent_col = "#8b5cf6"
        sale_green = "#22c55e"
        sale_bg = "rgba(34, 197, 94, 0.15)"
        btn_bg = "#7c3aed"
        btn_text = "#ffffff"
    else:  # Midnight (Default)
        bg_body = "#0d121f"
        bg_container = "#121827"
        bg_card = "#1a2238"
        border_col = "#1f293d"
        text_title = "#f8fafc"
        text_body = "#cbd5e1"
        text_muted = "#94a3b8"
        accent_col = "#6366f1"
        sale_green = "#4ade80"
        sale_bg = "rgba(74, 222, 128, 0.12)"
        btn_bg = "#4f46e5"
        btn_text = "#ffffff"

    # Filter Games
    if mode == "selected" and selected_ids:
        report_games = [g for g in games if g.get("id") in selected_ids or g.get("game_id") in selected_ids]
    elif mode == "tags" and selected_tags:
        report_games = []
        for g in games:
            normalize_game(g)
            g_tags = set(t.lower() for t in g.get("store_tags", []) + g.get("custom_tags", []))
            if g_tags.intersection(selected_tags):
                report_games.append(g)
    else:
        report_games = list(games)

    date_str = datetime.now().strftime("%A, %B %d, %Y")

    def _render_game_email_card(g: dict, is_hero: bool = False) -> str:
        name = g.get("name", "Unknown Game")
        store = g.get("store", "store")
        store_badge = _store_badge(store)
        cover = g.get("cover_image", "")
        url = g.get("url", "")
        curr_price = g.get("current_price")
        currency = g.get("current_currency", "INR")
        orig_price = g.get("original_price")
        disc = g.get("discount_percent") or 0
        is_sale = bool(g.get("is_on_sale")) or disc > 0
        lowest = g.get("lowest_price")
        lowest_curr = g.get("lowest_currency", currency)

        # Image or fallback title block
        if cover:
            img_html = f'<img src="{cover}" alt="{name}" style="width:100%;max-width:100%;height:auto;border-radius:8px;display:block;margin-bottom:12px;" />'
        else:
            img_html = f'<div style="background:{border_col};padding:16px;border-radius:8px;text-align:center;font-weight:700;color:{text_title};margin-bottom:12px;">🎮 {name}</div>'

        # Price Fields
        price_row = ""
        if enabled.get("current_price", True) and curr_price is not None:
            p_str = format_price(curr_price, currency)
            orig_str = f' <span style="text-decoration:line-through;color:{text_muted};font-size:13px;margin-left:6px;">{format_price(orig_price, currency)}</span>' if (enabled.get("original_price", True) and is_sale and orig_price and orig_price > curr_price) else ""
            disc_badge = f' <span style="background:{sale_bg};color:{sale_green};border:1px solid {sale_green};font-size:11px;font-weight:700;padding:2px 6px;border-radius:4px;margin-left:6px;">-{disc}% 🔥</span>' if (enabled.get("discount_percent", True) and is_sale and disc > 0) else ""
            price_row = f'<div style="font-size:18px;font-weight:800;color:{"#22c55e" if is_sale else text_title};margin-top:6px;">{p_str}{orig_str}{disc_badge}</div>'

        # Lowest Price
        lowest_row = ""
        if enabled.get("lowest_price", True) and lowest is not None:
            lowest_row = f'<div style="font-size:12px;color:{text_muted};margin-top:4px;">Lowest recorded: <strong style="color:{text_title};">{format_price(lowest, lowest_curr)}</strong></div>'

        # Price Change
        change_row = ""
        if enabled.get("price_change", True):
            diff = detect_price_change(history, g["id"], curr_price, currency)
            if diff is not None and abs(diff) > 0.01:
                diff_str = format_price(abs(diff), currency)
                change_color = sale_green if diff < 0 else "#ef4444"
                direction = "▼ Down by" if diff < 0 else "▲ Up by"
                change_row = f'<div style="font-size:12px;color:{change_color};font-weight:600;margin-top:4px;">{direction} {diff_str}</div>'

        # Tags
        normalize_game(g)
        tags_list = g.get("store_tags", []) + g.get("custom_tags", [])
        tags_html = ""
        if tags_list:
            tag_pills = "".join(f'<span style="display:inline-block;background:{border_col};color:{text_muted};font-size:10px;font-weight:600;padding:2px 6px;border-radius:4px;margin-right:4px;margin-top:4px;">{t}</span>' for t in tags_list[:4])
            tags_html = f'<div style="margin-top:6px;">{tag_pills}</div>'

        # CTA Button
        cta_button = ""
        if url:
            cta_button = f'<div style="margin-top:14px;text-align:right;"><a href="{url}" style="display:inline-block;background:{btn_bg};color:{btn_text};text-decoration:none;font-size:12px;font-weight:700;padding:8px 16px;border-radius:6px;">VIEW GAME &rarr;</a></div>'

        padding = "20px" if is_hero else "16px"
        margin = "20px" if is_hero else "12px"
        return f"""<div style="background:{bg_card};border:1px solid {border_col};border-radius:10px;padding:{padding};margin-bottom:{margin};">
{img_html}
<div style="display:flex;justify-content:space-between;align-items:center;">
<span style="font-size:16px;font-weight:800;color:{text_title};">{name}</span>
{store_badge}
</div>
{tags_html}
{price_row}
{lowest_row}
{change_row}
{cta_button}
</div>"""

    # Section 1: ⭐ Featured Game
    featured_html = ""
    if featured_id:
        fg = next((g for g in games if g.get("id") == featured_id or g.get("game_id") == featured_id), None)
        if fg:
            featured_html = f"""<tr><td style="padding-bottom:20px;">
<div style="color:{accent_col};font-size:12px;font-weight:800;letter-spacing:1px;text-transform:uppercase;margin-bottom:8px;">⭐ TODAY'S FEATURED GAME</div>
{_render_game_email_card(fg, is_hero=True)}
</td></tr>"""

    # Section 2: 🔥 NEW DEALS
    new_deals_html = ""
    if enabled.get("new_sales", True):
        deals = [g for g in report_games if g.get("is_on_sale") or (g.get("discount_percent") or 0) > 0]
        if deals:
            cards = "".join(_render_game_email_card(g) for g in deals[:5])
            new_deals_html = f"""<tr><td style="padding-bottom:20px;">
<h2 style="color:{text_title};font-size:16px;font-weight:700;margin:0 0 12px 0;">🔥 NEW DEALS ({len(deals)})</h2>
{cards}
</td></tr>"""

    # Section 3: 🏆 LOWEST PRICES
    lowest_prices_html = ""
    if enabled.get("lowest_price_alerts", True):
        lows = [g for g in report_games if g.get("current_price") is not None and g.get("current_price") == g.get("lowest_price")]
        if lows:
            cards = "".join(_render_game_email_card(g) for g in lows[:5])
            lowest_prices_html = f"""<tr><td style="padding-bottom:20px;">
<h2 style="color:{text_title};font-size:16px;font-weight:700;margin:0 0 12px 0;">🏆 LOWEST PRICES ({len(lows)})</h2>
{cards}
</td></tr>"""

    # Section 4: ⚖️ STEAM VS EPIC COMPARISON
    comparison_html = ""
    if enabled.get("store_comparison", True):
        comp_content = _cross_store_deals_section(report_games)
        if "No games tracked" not in comp_content:
            comparison_html = f"""<tr><td style="padding-bottom:20px;">
<h2 style="color:{text_title};font-size:16px;font-weight:700;margin:0 0 12px 0;">⚖️ STEAM VS EPIC COMPARISON</h2>
<div style="background:{bg_card};border:1px solid {border_col};border-radius:10px;padding:16px;color:{text_body};">
{comp_content}
</div>
</td></tr>"""

    # Section 5: All Filtered Tracked Game Cards
    games_cards_html = ""
    if report_games:
        cards_list = "".join(_render_game_email_card(g) for g in report_games)
        games_cards_html = f"""<tr><td style="padding-bottom:20px;">
<h2 style="color:{text_title};font-size:16px;font-weight:700;margin:0 0 12px 0;">📋 TRACKED GAMES ({len(report_games)})</h2>
{cards_list}
</td></tr>"""
    else:
        games_cards_html = f"""<tr><td style="padding:20px;text-align:center;color:{text_muted};">
Nothing to report today. No tracked games match your current filter settings.
</td></tr>"""

    body = f"{featured_html}{new_deals_html}{lowest_prices_html}{comparison_html}{games_cards_html}"

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:{bg_body};font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:{bg_body};">
<tr><td align="center" style="padding:20px 12px;">
<table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:{bg_container};border-radius:16px;padding:28px;border:1px solid {border_col};box-shadow:0 8px 32px rgba(0,0,0,0.4);">
<!-- HEADER -->
<tr><td style="text-align:center;padding-bottom:20px;border-bottom:1px solid {border_col};margin-bottom:20px;">
<h1 style="color:{text_title};font-size:24px;margin:0;font-weight:800;letter-spacing:-0.5px;">{report_title}</h1>
<p style="color:{text_muted};font-size:13px;margin:6px 0 0 0;">{date_str}</p>
<p style="color:{text_muted};font-size:12px;margin:4px 0 0 0;font-style:italic;">Your tracked games, current deals, and price changes.</p>
</td></tr>
<tr><td style="height:20px;"></td></tr>
{body}
<!-- FOOTER -->
<tr><td style="text-align:center;padding-top:20px;border-top:1px solid {border_col};">
<p style="color:{text_muted};font-size:11px;margin:0 0 4px;letter-spacing:0.5px;">GENERATED BY GAME PRICE TRACKER</p>
<p style="color:{text_muted};font-size:10px;margin:0 0 8px;">Checked: Steam &middot; Epic Games &middot; GOG</p>
<p style="color:{text_muted};font-size:10px;margin:0;">See you tomorrow!</p>
</td></tr>
</table>
</td></tr>
</table>
</body>
</html>"""

